apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: evgeny88docker/config-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  ports:
    - targetPort: 9000
      port: 80
  selector:
    app: config-service