apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data'
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-volume
  name: db-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marketplace-db
spec:
  selector:
    matchLabels:
      app: marketplace-db
  serviceName: marketplace-db
  replicas: 1
  template:
    metadata:
      labels:
        app: marketplace-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: marketplace-db
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: host-config
                  key: SERVICE_HOST_CUBER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASS
          volumeMounts:
            - name: db-volume
              mountPath: '/data/postgres/marketplace-db'
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-volume-claim
---

apiVersion: v1
kind: Service
metadata:
  name: marketplace-db
  labels:
    app: marketplace-db
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30032
      port: 5432
      targetPort: 5432
      name: marketplace
  selector:
    app: marketplace-db















