global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'marketplace_services'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'auth-service-api-dev'
          - 'profile-service-api-dev'
        type: 'A'
        port: 8080
