apiVersion: v1
kind: Service
metadata:
  name: redis-primary-svc
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
      nodePort: 30010
  selector:
    name: redis-primary
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: redis-replica-svc
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
      nodePort: 30011
  selector:
    name: redis-replica
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-primary
  labels:
    name: redis-primary
    app: redis
spec:
  replicas: 1
  serviceName: redis-primary-svc
  selector:
    matchLabels:
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          env:
            - name: REDIS_HOST
              value: redis-primary-0
            - name: redis_pass
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASS
          command:
            - "redis-server"
          args:
            - "--requirepass"
            - "$(redis_pass)"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: datadir
              mountPath: /data/redis_data
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app: redis
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10Mi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  labels:
    name: redis-replica
    app: redis
spec:
  serviceName: redis-replica-svc
  replicas: 2
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          env:
            - name: redis_pass
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASS
          command:
            - "redis-server"
          args:
            - "--slaveof"
            - "redis-primary-svc"
            - "6379"
            - "--masterauth"
            - "$(redis_pass)"
          volumeMounts:
            - name: datadir
              mountPath: /data/redis_data
          ports:
            - containerPort: 6379
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app: redis
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 10Mi

