apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
        - name: zipkin-server
          image: openzipkin/zipkin
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin-server
  name: zipkin-server
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30001
      protocol: TCP
  selector:
    app: zipkin-server


