server:
  port: 8888
spring:
  application:
    name: common-config-service
  cloud.config.server:
    git:
      uri: https://github.com/Evgeny0088/marketplace-reactive-configs
      searchPaths: configs/{application}
      default-label: main
