server:
  port: 8888

spring:
  application:
    name: common-config-sever
  cloud.config.server:
    git:
      uri: https://github.com/Evgeny0088/marketplace-reactive-configs.git
      search-paths:
        - configs/{application}
        - configs/