apiVersion: v1
kind: ConfigMap
metadata:
  name: host-config
data:
  SERVICE_HOST_CUBER: {{SERVICE_HOST_CUBER}} 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  ADVERTISED_LISTENERS: "INTERNAL://kafka-service:9092,EXTERNAL://:30092"
  LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
  ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  PLAINTEXT_LISTENER: "yes"
  INTERNAL_LISTENER_NAME: "INTERNAL"
  TOPIC_REPLICATION_FACTOR: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_PASS: {{REDIS_PASS}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: {{DB_NAME}}
  POSTGRES_USER: {{DB_USER}}
  POSTGRES_PASS: {{DB_PASS}}

  
