spring:
  application.name: gateway-service-api
  zipkin.enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-ignore: ignore-unknown
    deserialization:
      fail-on-unknown-properties: false

com.marketplace:
  gateway:
    serverUrl: http://localhost
    stand: host
    port: 8080
    auth:
      marketplace-name: marketplace-app
      marketplace-pass: marketplace-pass

service-road-map:
    service: (?<service>.*?)
    auth-not-required-url-list:
        - ${service-road-map.service}/auth/update-profile/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/confirm
        - ${service-road-map.service}/api-docs/*
    blackListWords:
        - internal
        - admin
        - actuator
    services:
        -   # authentication services
            alias: auth
            name: local
            port: 8081
            authRequired: false

        -   # profile services
            alias: profile
            name: local
            port: 8082
            authRequired: true