apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque
data:
  POSTGRES_HOST: {{DB_HOST}}
  POSTGRES_DB: {{DB_NAME}}
  POSTGRES_USER: {{DB_USER}}
  POSTGRES_PASS: {{DB_PASS}}

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: default
type: Opaque
data:
  REDIS_PASS: {{REDIS_PASS}}
  REDIS_HOST: {{REDIS_HOST}}


