loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: standard
    size: 10Mi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
